language: bash  # Specify the language as bash since we're using a bash script

os: linux
dist: jammy  # Use Ubuntu 22.04

services:
  - docker  # Enable Docker service

jobs:
  include:
    - name: "Docker Build"
      resources:
        requests:
          cpu: 2
          memory: 8G

script:
  - ./build_docker.sh
