version: '3.8'

services:
  flask-app:
    # Change the path to suitable Docker image
    image: "flask-app:latest"
    ports:
        # Change the port if neccessary
      - "5000:5000"
    volumes:
        # Mount the current folder as folder for saving database. You can change to other path on your favor
      - .:/database
      - .:/cert
    environment:
      - FLASK_ENV=production
      - CERT_PATH=/cert/qtry.crt # replace your crt here make sure
      - CERT_KEY_PATH=/cert/qtry.key  # replace your key here make sure
    # Additional command is
    # options:
    #-h, --help          show this help message and exit
    #-appport APPPORT    The port of this app
    #-nodeip NODEIP      Node IP address
    #-nodeport NODEPORT  Node port number
    #-dbpath DBPATH      Directory contain the database file
    #-debug              Enable debug mode (default: False)
    command: ["python3", "app.py", "-dbpath", "/database"]
