version: '3.8'

services:
  flask-app:
    # Change the path to suitable Docker image
    image: "ghcr.io/icyblob/flask-app:latest"
    ports:
        # Change the port if neccessary
      - "5000:5000"
    volumes:
        # Mount the current folder as folder for saving database. You can change to other path on your favor
      - .:/database
      - .:/cert
    environment:
      - FLASK_ENV=production
      - CERT_PATH=/cert/qtry.crt      # replace your crt here
      - CERT_KEY_PATH=/cert/qtry.key  # replace your key here
      - NODE_IP=5.199.134.150         # example node IP. Replace with the real IP
      - NODE_PORT=31844               # example node port. Replace with the real port
      - DATABASE_PATH=/database
    command: ["python3", "app.py"]
