x-common-env: &common-env DATABASE_PATH=/database

services:
  server_backup:
    image: "flask-app"
    ports:
      - "8080:80"
    volumes:
      - ./bet_external_asset:/app/bet_external_asset
    command: ["python", "backup_server.py"]
  flask-app:
    # Change the path to suitable Docker image
    image: "flask-app"
    ports:
      - 80:5000
    volumes:
        # Mount the current folder as folder for saving database. Make sure you mount the same folder with db-updater
      - .:/database:ro
      - .:/cert:ro
      - /home/user/icyblob/workspace/bet_sync/bet_external_asset:/bet_external_asset:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - FLASK_ENV=production
        #- CERT_PATH=/cert/cert.pem      # replace your crt here
        #- CERT_KEY_PATH=/cert/key.pem  # replace your key here
      - *common-env
    command: ["python", "app.py"]
    restart: always

