name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Update Submodules and Build Docker
      run: git submodule update --recursive --init && ./build_docker.sh

    - name: Start Docker Compose with Timeout
      run: |
        timeout 30s docker-compose up &
        sleep 30
        docker-compose down
