name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Update Submodules and Build Docker
      run: git submodule update --recursive --init && ./build_docker.sh

    - name: Generate SSL Certificates
      run: |
        openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes -keyout qtry.key -out qtry.crt -subj "/CN=example.com" -addext "subjectAltName=DNS:example.com,DNS:*.example.com,IP:10.0.0.1"
    
    - name: Start Docker Compose with Timeout and Check for Errors
      run: |
        timeout 30s docker-compose up -d
        docker-compose logs
        docker-compose ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | grep -q '^0$' || exit 1
    
    - name: Docker Compose Down
      if: always()
      run: |
        docker-compose down
